name: Coveralls

on: [push, pull_request]

jobs:
  coveralls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Coverage
        run: make coverage
      - name: Upload coverage results to Coveralls
        env:
            COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            docker-compose run --rm php-8.1 vendor/bin/php-coveralls
