name: Coveralls

on: [push, pull_request]

jobs:
  coveralls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Coveralls
        run: docker-compose run --rm -e COVERALLS_REPO_TOKEN php-8.1 sh -c 'echo $COVERALLS_REPO_TOKEN'
